### ISSUE TITLE
Cannot find module for path io/fs

### ISSUE THREAD

**Issue by bart-roos** [dtact/divd-2021-00038--log4j-scanner#1]
Could it be that a module dependency for  path io/fs is missing? 

Trying to run the code I get the following error:

```
$ go run .
build github.com/dutchcoders/divd-2021-00038--log4j-scanner: cannot find module for path io/fs
```

I have absolutely 0 experience with Golang, so forgive me if this is just an user error.

**Comment by nl5887** [comment]
No worries, this is probably related to an old Go version.

**Comment by nl5887** [comment]
Updated documentation to use GO > 1.16
