### ISSUE TITLE
Avoid unlikely directories by default

### ISSUE THREAD

**Issue by sanmai-NL** [dtact/divd-2021-00038--log4j-scanner#11]
If you scan the full filesystem under Linux, the tool also scans e.g., `/sys/`. I think it's better to skip some paths by default.

**Comment by nl5887** [comment]
Not completely agree with you, as you'll never know for sure where files will end up. Currently there is an `--exclude` flag that will allow users to define their own paths to skip.

**Comment by sanmai-NL** [comment]
When would Log4j2 end up under `/sys/` or `/proc/`?

**Comment by nl5887** [comment]
Good point. Added exclusions for `/proc`, `/net`, `/sys` and `/dev`.
