### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ykanello** [dtact/divd-2021-00038--log4j-scanner#4]
Running on Darwin.
The scanner crashed while scanning a large fileset.
`[!][/xxxxxx/xxxxxx/xxxxxx/Library/Caches/Homebrew/downloads/2ac97b815131569d7888e06425f3446be8b2e68f8361ce20c65051f66cb23360--qt--6.2.2.monterey.bottle.tar.gz -> qt/6.2.2/share/qt/mkspecs/features/link_pkgconfig.prf] could not open zip file 1fe46b14df7175167596e630a8b1160a3e3e82d7bf62299b3acebd689a83675b
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x112eee8]`

**Comment by ykanello** [comment]
goroutine 1 [running]:
github.com/dutchcoders/divd-2021-00038--log4j-scanner/app.(*fuzzer).RecursiveFind(0xc00007f520, {0xc000012980, 0xc0006774e0, 0x1}, {0xc000583660, 0x2, 0x20}, {0x0, 0x0})
        /Users/xxxx/divd-2021-00038--log4j-scanner/app/app.go:427 +0x68
github.com/dutchcoders/divd-2021-00038--log4j-scanner/app.(*fuzzer).RecursiveFind.func1({0x2a749940, 0xc000b5e0f0}, 0xc00007f520, {0xc000210000, 0x1, 0x1})
        /Users/xxxx/divd-2021-00038--log4j-scanner/app/app.go:494 +0x994
github.com/dutchcoders/divd-2021-00038--log4j-scanner/app.(*fuzzer).RecursiveFind(0xc00007f520, {0xc000210000, 0x9351c59, 0x20}, {0xc0069d8000, 0x0, 0x20}, {0x121c2c0, 0xc000010048})
        /Users/xxxx/divd-2021-00038--log4j-scanner/app/app.go:519 +0x6b8
github.com/dutchcoders/divd-2021-00038--log4j-scanner/app.(*fuzzer).RecursiveFind.func1({0x1beb028, 0xc000205680}, 0xc00007f520, {0xc000677988, 0x0, 0x0})
        /Users/xxxx/divd-2021-00038--log4j-scanner/app/app.go:504 +0xdad
github.com/dutchcoders/divd-2021-00038--log4j-scanner/app.(*fuzzer).RecursiveFind(0xc00007f520, {0xc000677988, 0xc000010018, 0x11e0dce}, {0x138d450, 0xc0001759c0, 0x0}, {0x121c2a0, 0xc0000535c0})
        /Users/xxxx/divd-2021-00038--log4j-scanner/app/app.go:519 +0x6b8
github.com/dutchcoders/divd-2021-00038--log4j-scanner/app.(*fuzzer).Run(0xc00007f520)
        /Users/xxxx/divd-2021-00038--log4j-scanner/app/app.go:558 +0x71b
github.com/dutchcoders/divd-2021-00038--log4j-scanner/cmd.New.func2(0xc00018c000)
        /Users/xxxx/divd-2021-00038--log4j-scanner/cmd/cmd.go:166 +0x705
github.com/urfave/cli.HandleAction({0x11a5ba0, 0x11eb228}, 0x1)
        /Users/xxxx/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0xa8
github.com/urfave/cli.(*App).Run(0xc00014e1c0, {0xc000012040, 0x2, 0x2})
        /Users/xxxx/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:286 +0x625
github.com/urfave/cli.(*App).RunAndExitOnError(0xc00014e1c0)
        /Users/xxxx/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:298 +0x37
main.main()
        /Users/xxxx/divd-2021-00038--log4j-scanner/main.go:7 +0x25

**Comment by nl5887** [comment]
seems to be fixed with commit 287fc6e6f0dd4c35f1764c89279cba07309c82c0 or 4147dba6d5841584fc0702e5db2af34ed73af6fd

**Comment by ykanello** [comment]
[ ] Checked 1934460 files in 01h35m2086s, average rate is: 55629 files/min.
BTW I still got few stderr logs on screen
